# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes for Airline
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Airline
  # ---------------------------------------------------------------------------
  - Name: Airline
    Domain: airline.example.com
    EnableNodeOUs: true
    # Specs for defining explicit peers
    Specs:
      - Hostname: QA3.1
    # Users
    Users:
      Count: 1