# This file is specifically focused on setting up the Certificate Authorities (CAs) for the network. The Certificate Authorities are responsible for issuing and managing the digital certificates for network participants, which are crucial for the authentication and authorization mechanisms in Hyperledger Fabric. However, based on the provided content, it appears that the specific configurations for the CAs were not included in the snippet. Typically, this file would include:

# CA Services: Each organization in the network would have its own CA service defined in this file. The service configuration would specify the Docker image for the CA (hyperledger/fabric-ca:latest), environment variables for CA configuration, ports for accessing the CA, and volumes for data persistence.
# Environment Variables: Used to configure the CA, such as setting the home directory, CA name, and enabling TLS.
# Ports: Specifies the ports that the CA services will listen on, allowing network participants to communicate with the CA for operations like enrolling and registering identities.
# In summary, the docker-compose-test-net.yaml file is used to configure and launch the core network components (peers, orderers, etc.), while the docker-compose-ca.yaml file is focused on setting up the Certificate Authorities necessary for managing identities within the network. Both are essential for deploying a functioning Hyperledger Fabric network environment using Docker.

version: '3.7'

networks:
  test:
    name: fabric_test

services:
  # CA for OEM
  ca_oem:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-oem
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=11054
    ports:
      - "11054:11054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/oem:/etc/hyperledger/fabric-ca-server
    container_name: ca_oem
    networks:
      - test

  # CA for Airline
  ca_airline:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-airline
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=12054
    ports:
      - "12054:12054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/airline:/etc/hyperledger/fabric-ca-server
    container_name: ca_airline
    networks:
      - test

  # CA for Supplier
  ca_supplier:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-supplier
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=13054
    ports:
      - "13054:13054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/supplier:/etc/hyperledger/fabric-ca-server
    container_name: ca_supplier
    networks:
      - test