# This file is used to define and configure the network components necessary for a Hyperledger Fabric test network. It specifies the Docker containers that will run the Fabric peer nodes, orderer nodes, and other necessary services for the network to function. The configuration includes:

# Peer Services: Defines the peer nodes for the organizations in the network. For example, peer0.org1.example.com and peer0.org2.example.com are defined as peers for two different organizations. Each peer service configuration includes the Docker image to use (hyperledger/fabric-peer:latest), environment variables to configure the peer, and volumes for data persistence and configuration.
# Volumes: Specifies the directories on the host that are mounted into the containers. This is used for configuration files and to ensure data persistence across container restarts.
# Network Settings: Defines the Docker network settings, such as the network mode, to ensure that all containers can communicate with each other.
version: '3.7'
services:
  # OEM Organization Peers
  QA1.1.oem.example.com:
    container_name: QA1.1.oem.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock

  QA1.2.oem.example.com:
    container_name: QA1.2.oem.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock

  SW1.1.oem.example.com:
    container_name: SW1.1.oem.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock

  SW1.2.oem.example.com:
    container_name: SW1.2.oem.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock

  SW1.3.oem.example.com:
    container_name: SW1.3.oem.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock

  # Supplier Organization Peer
  QA2.1.supplier.example.com:
    container_name: QA2.1.supplier.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock

  # Airline Organization Peer
  QA3.1.airline.example.com:
    container_name: QA3.1.airline.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock

  # CLI container for operations
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode:/opt/gopath/src/github.com/hyperledger/fabric-samples/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric-samples/scripts
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric-samples/channel-artifacts


#Labels
#Purpose: Labels in Docker are key-value pairs attached to objects such as containers, images, volumes, etc. They serve as a way to organize, categorize, and apply metadata that can be used for filtering and management purposes.
# Absence in Some Services: The absence of labels like service: hyperledger-fabric in certain parts of the Docker Compose file doesn't impact the functionality of the network. Labels are optional and are used for specific purposes, such as simplifying the management of Docker objects or for use with Docker Swarm for service discovery and orchestration. In the context of the Hyperledger Fabric test network, labels might be used for organizational purposes but are not strictly necessary for the network's operation.
# Volumes
# Purpose: Volumes are used in Docker to persist data generated by and used by Docker containers. In the context of Hyperledger Fabric, volumes are crucial for several reasons:
# Persistence: They ensure that important data such as blockchain ledger data, chaincode (smart contracts), and cryptographic material remains intact across container restarts.
# Security: By storing cryptographic material and other sensitive data in volumes, it helps in isolating and protecting this data.
# Configuration and Data Sharing: Volumes are used to share configuration files and other necessary data between the host and containers or among containers themselves. This is essential for setting up the network configuration, MSP (Membership Service Provider) data, and chaincode.
# Multiple Volumes: Each service in the Docker Compose file, such as peers, orderers, and CLI tools, requires access to different sets of data and configurations. This necessitates defining multiple volumes. For example:
# Orderer and Peer Nodes: Need access to their MSP data for identity and access control, ledger data for the blockchain state, and certificates for TLS communication.
# CLI Container: Requires access to scripts, chaincode, and cryptographic material to interact with the network for administrative tasks, chaincode installation, and invoking transactions.